language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - apt-get install git-lfs
script:
  - pytest --cov=../ ../
before_script:
  - echo -e "machine ghttps://github.com/IbrahimNM/iSeefood  login $gitLfs" > ~/.netrc
  - git lfs checkout
  - git lfs --version
  - git lfs pull
after_success:
  - codecov --token=$codecovReport
