language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./
before_script: 
  - cd $TRAVIS_BUILD_DIR/iSeefood/iSeefood/
after_success:
  - codecov --token=ab8871f6-60b5-4e07-b55f-2ef1bd1e4f44
