language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
git:
  lfs_skip_smudge: false
script:
  - pytest --cov=../ ../
before_script: true
after_success:
  - codecov --token=$codecovReport
